### ISSUE TITLE
Struggles

### ISSUE THREAD

**Issue by tchi0007** [tchi0007/accessibility-fixer-upper#1]
Hi Christina, 

Im wondering if you can help explain these markbot issues I keep getting. I'm not sure what to look for as I have id's for those links and I have a tabindex. 

<img width="917" alt="Screen Shot 2020-04-19 at 11 23 12 AM" src="https://user-images.githubusercontent.com/43075225/79691981-7b7c3480-8230-11ea-90da-a78ef57e822f.png">

Thanks, 
Sara

@muxlowc

**Comment by muxlowc** [comment]
@tchi0007 yah so there's actually a typo in that first part, so don't worry about that (i'll give you the mark manuallyy)

As for that second issue, it looks like you're missing tabindex="0" on your contact section. So just go ahead and add that, and ill go and giv eyou the mark :)

Good job!
